### ISSUE TITLE
Множественное назначение системных ролей на странице пользователей

### ISSUE THREAD

**Issue by zubrailx** [itmo-events-app/frontend#74]
![image](https://github.com/itmo-events-app/frontend/assets/69198006/4cd4c873-92b0-4d2f-ba4d-0f7ed33a7d62)

Вот тут надо добавить возможность назначения.

Тогда необходимо переименовать отозвать роль в отозвать все роли и назначить роль в редактировать роли:

![image](https://github.com/itmo-events-app/frontend/assets/69198006/8778ae43-27b7-41ae-8bcd-e96ba1a0414a)

**Comment by Darklol** [comment]
Изменения готовы, нужно одобрить ПР на беке и фронте (а также обновить АПИ после того как бек одобрят)

https://github.com/itmo-events-app/frontend/pull/104
https://github.com/itmo-events-app/event-app/pull/123

**Comment by Darklol** [comment]
Теперь выглядит так
![image](https://github.com/itmo-events-app/frontend/assets/58745426/50bb0c24-1963-4f04-aa5d-6ee64a43fa3a)
![image](https://github.com/itmo-events-app/frontend/assets/58745426/fda54f95-0b3c-4502-9bdc-1f2832475bef)
