### ISSUE TITLE
Починить страницу редактирования мероприятий

### ISSUE THREAD

**Issue by zubrailx** [itmo-events-app/frontend#79]
![image](https://github.com/itmo-events-app/frontend/assets/69198006/60d4b3fa-bace-46ab-a68c-d4165b1801fb)

Тут не получается сделать успешный ввод формы, с бека не приходит нужный ответ.

Кроме того:
- при выборе формата и состояния, если они изначально не заданы, следует инициализировать эти пропсы дефолтными значениями как на странице выше (там вроде первый элемент списка).

```typescript
  const [format, setFormat] = useState(getAddActivityFormatEnum(eventInfo.format!)); // TODO: в случае, если формат не задан, то выбрать первое значение как в select-е
  const [status, setStatus] = useState(getAddActivityStatusEnum(eventInfo.status!));
```

Аналогично проверить остальные элементы формы на наличие похожих ошибок

**Comment by LiaoYihong-1** [comment]
![微信截图_20240417132645](https://github.com/itmo-events-app/frontend/assets/74876152/6ff5979e-96f0-4067-b827-85ca31113cdd)
![微信截图_20240417132701](https://github.com/itmo-events-app/frontend/assets/74876152/3a677a0d-0e39-4e8e-82ef-49177f63ca53)
