### ISSUE TITLE
Редактирование списка участников и смена явки

### ISSUE THREAD

**Issue by zubrailx** [itmo-events-app/frontend#81]
![image](https://github.com/itmo-events-app/frontend/assets/69198006/22fb1651-a203-4e74-a707-d12d96650170)

Если работает файл, то ок. Кроме того добавить:
- кнопка отметить, что все присутствуют
- кнопка отметить, что никого не было

Бек с явкой работает?

**Comment by anamrzv** [comment]
Не работает вроде
