### ISSUE TITLE
Создание задач и их редактирование со страницы мероприятия + УДАЛЕНИЕ

### ISSUE THREAD

**Issue by zubrailx** [itmo-events-app/frontend#82]
![image](https://github.com/itmo-events-app/frontend/assets/69198006/6d0e0693-105b-4e86-a03f-8bc0bc82ecfa)

Этого нет, делайте как хотите, но через модалку.

То есть и создание и редактирование задач как на глобальной странице Задачи. Чтобы можно было делать все как она просила. И привилегии туда же, и еще что-то кому-то куда-то. Я устал писать

**Comment by anamrzv** [comment]
Еще удаление задачи!!!
